[package]
name = "radix"
version = "0.3.3"
authors = ["Joey Ezechiëls <joey.ezechiels@gmail.com>"]
description = "Convert any {u8, u16, u32, u64, usize} to another radix"
license = "MIT"
repository = "http://github.com/jjpe/radix"

[dependencies]
